using AIWorkflowAssistant.Api.DTOs;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using QuestPDF.Fluent;
using QuestPDF.Infrastructure;
using OpenXmlDocument =
    DocumentFormat.OpenXml.Wordprocessing.Document;

namespace AIWorkflowAssistant.Api.Services.FileGeneration;

public class DocumentFileGenerator : IDocumentFileGenerator
{
    private readonly IWebHostEnvironment _environment;

    public DocumentFileGenerator(IWebHostEnvironment environment)
    {
        _environment = environment;
    }

    public async Task<string> GenerateDocxAsync(
        string originalFileName,
        AiSummaryDto aiResult)
    {
        var outputDirectory = GetOutputDirectory();

        Directory.CreateDirectory(outputDirectory);

        var baseName = Path.GetFileNameWithoutExtension(
            originalFileName);

        var outputFileName =
            $"{baseName}-ai-summary.docx";

        var outputPath = Path.Combine(
            outputDirectory,
            outputFileName);

        using (var document = WordprocessingDocument.Create(
            outputPath,
            WordprocessingDocumentType.Document))
        {
            var mainPart = document.AddMainDocumentPart();

            mainPart.Document = new OpenXmlDocument(
                new Body(
                    CreateTitle(
                        "AI Workflow Assistant - Document Summary"),

                    CreateHeading("Summary"),

                    CreateParagraph(aiResult.Summary),

                    CreateHeading("Action Items"),

                    CreateActionItems(aiResult.ActionItems)
                ));

            mainPart.Document.Save();
        }

        await Task.CompletedTask;

        return GetRelativePath(outputPath);
    }

    public async Task<string> GeneratePdfAsync(
        string originalFileName,
        AiSummaryDto aiResult)
    {
        var outputDirectory = GetOutputDirectory();

        Directory.CreateDirectory(outputDirectory);

        var baseName = Path.GetFileNameWithoutExtension(
            originalFileName);

        var outputFileName =
            $"{baseName}-ai-summary.pdf";

        var outputPath = Path.Combine(
            outputDirectory,
            outputFileName);

        QuestPDF.Settings.License =
            LicenseType.Community;

        QuestPDF.Fluent.Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(40);

                page.Header()
                    .Text("AI Workflow Assistant")
                    .FontSize(20)
                    .Bold();

                page.Content()
                    .Column(column =>
                    {
                        column.Spacing(15);

                        column.Item()
                            .Text("Document Summary")
                            .FontSize(16)
                            .Bold();

                        column.Item()
                            .Text(aiResult.Summary)
                            .FontSize(11);

                        column.Item()
                            .Text("Action Items")
                            .FontSize(16)
                            .Bold();

                        foreach (var actionItem
                                 in aiResult.ActionItems)
                        {
                            column.Item()
                                .Text($"• {actionItem}")
                                .FontSize(11);
                        }
                    });

                page.Footer()
                    .AlignCenter()
                    .Text("Generated by AI Workflow Assistant");
            });
        })
        .GeneratePdf(outputPath);

        await Task.CompletedTask;

        return GetRelativePath(outputPath);
    }

    private string GetOutputDirectory()
    {
        return Path.Combine(
            _environment.ContentRootPath,
            "GeneratedFiles");
    }

    private string GetRelativePath(string fullPath)
    {
        return Path.GetRelativePath(
            _environment.ContentRootPath,
            fullPath);
    }

    private static Paragraph CreateTitle(string text)
    {
        return new Paragraph(
            new ParagraphProperties(
                new Justification
                {
                    Val = JustificationValues.Center
                }),
            new Run(
                new RunProperties(
                    new Bold(),
                    new FontSize
                    {
                        Val = "32"
                    }),
                new Text(text)));
    }

    private static Paragraph CreateHeading(string text)
    {
        return new Paragraph(
            new Run(
                new RunProperties(
                    new Bold(),
                    new FontSize
                    {
                        Val = "24"
                    }),
                new Text(text)));
    }

    private static Paragraph CreateParagraph(string text)
    {
        return new Paragraph(
            new Run(
                new Text(text ?? string.Empty)));
    }

    private static Paragraph CreateActionItems(
        List<string> actionItems)
    {
        var paragraph = new Paragraph();

        foreach (var actionItem in actionItems)
        {
            paragraph.Append(
                new Run(
                    new Text($"• {actionItem}")));

            paragraph.Append(new Break());
        }

        return paragraph;
    }
}